ECommerceCommunity/FeedShop_Frontend

package.json
src/App.tsx
src/pages/ProductDetailPage.tsx
src/pages/ReportManagePage.tsx

프론트 기초 UI 및 세팅
- 리뷰 추가 및 styledcomponents 버전 변경

리뷰추가및styledcomponents버전변경

---

package.json
src/pages/CartPage.tsx

cart 페이지 useNavigate 추가 PR 테스트

장바구니 페이지 연결

---

package-lock.json
package.json
src/App.tsx
src/pages/AdminDashboardPage.tsx
src/pages/CartPage.tsx
src/pages/CheckoutPage.tsx
src/pages/HomePage.tsx
src/pages/PaymentPage.tsx
src/pages/ProductDetailPage.tsx
src/pages/ReportManagePage.tsx
src/pages/StoreHomePage.tsx

장바구니/주문 및 결제 페이지 추가 및 수정

---

package-lock.json
package.json
src/App.tsx
src/api/axios.ts
src/components/layout/Header.tsx
src/components/layout/Sidebar.tsx
src/contexts/AuthContext.tsx
src/pages/LoginPage.tsx
yarn.lock

MYCE-45 로그인 api 연동

---

package-lock.json
package.json
src/App.tsx
src/api/axios.ts
src/components/layout/Header.tsx
src/components/layout/Sidebar.tsx
src/contexts/AuthContext.tsx
src/pages/LoginPage.tsx
yarn.lock

feat : 로그인 API 연동 기능 구현

---

src/App.tsx
src/pages/products/DetailPage.tsx
src/pages/reviews/ReviewEditPage.tsx
yarn.lock

📌 주요 변경 사항
리뷰 작성 페이지 레이아웃 및 스타일 구성
카테고리 선택, 리뷰 제목, 평점, 상품 평가, 체크포인트, 상세 설명, 이미지 업로드 기능 추가
각 항목에 대한 유효성 표시 (*로 필수 항목 표시)
텍스트 입력 시 글자 수 실시간 표시 (최대 2000자)
이미지 미리보기 기능 구현 (최대 10장)
평가 항목(사이즈/쿠션감/지지력) 라디오 버튼 스타일 커스터마이징
✅ 구현 기능
스타일 구성: styled-components를 활용한 반응형 레이아웃 및 박스 형태 UI
상품 평가: 5점 척도 평가 라디오 버튼과 세부 항목 텍스트 표시
이미지 업로드: 드래그 or 클릭으로 이미지 업로드 및 미리보기 가능
입력 유효성: 필수 항목 및 텍스트 길이 제한 설정

Add: 상품마다 리뷰 작성 버튼 및 작성 페이지 구현

---

package-lock.json
package.json
src/App.tsx
src/pages/products/DetailPage.tsx
yarn.lock

feat: App.tsx + DetailPage.tsx 파일 수정

---

package-lock.json
package.json
src/App.tsx
src/pages/products/DetailPage.tsx
yarn.lock

App.tsx + DetailPage.tsx 파일수정 및 충돌확인

MYCE-79-dosik-feat-reviews: App.tsx+DetailPage.tsx 파일 수정 및 충돌확인

---

src/App.tsx
src/components/layout/Header.tsx
src/components/modal/SuccessModal.tsx
src/contexts/AuthContext.tsx
src/pages/AdminDashboardPage.tsx
src/pages/BecomeAdminPage.tsx
src/pages/HomePage.tsx
src/pages/LoginPage.tsx
src/pages/SignUp.tsx
src/pages/SignUpPage.tsx
src/pages/event/EventDetailPage.tsx
src/pages/event/EventListPage.tsx
src/pages/feed/FeedListPage.tsx
src/pages/feed/MyFeedPage.tsx
src/utils/auth.js
src/utils/auth.ts

1. **회원가입/로그인 페이지 개선**
- SignUp, SignUpPage, LoginPage의 UI/UX 개선 및 입력 검증 강화
- 소셜 로그인/회원가입 버튼 스타일 및 Divider 컴포넌트 공통화
- 회원가입 성공 시 SuccessModal로 안내
2. **관리자/판매자 관련 기능 리팩토링**
- BecomeSellerPage → BecomeAdminPage로 파일명 및 내용 변경
- AdminDashboardPage UI 및 기능 개선
3. **공통 레이아웃 및 인증 연동**
- Header 컴포넌트에서 인증 상태에 따라 메뉴 노출 및 UI 개선
- AuthContext 인증 로직 리팩토링
4. **코드 품질 및 오류 수정**
- styled-components의 keyframes 애니메이션(fadeInUp, slideInLeft, float) 정의 추가
- Divider, SocialLoginButton 등 공통 styled 컴포넌트 정의 및 재사용
- async/await 관련 await 오류 수정 (SignUpPage 등)
- 코드 정리 및 불필요 코드 제거
- 회원가입, 로그인, 관리자 전환, 관리자 대시보드 접근 등 주요 플로우 정상 동작 확인

MYCE-15 feat: 회원가입/로그인 페이지 개선

---

.gitignore
src/App.tsx
src/pages/auth/FindAccountPage.tsx
src/pages/auth/FindPasswordPage.tsx
src/pages/auth/LoginPage.tsx

계정 및 비밀번호 찾기 페이지를 추가하고 관련 라우팅 및 링크를 설정합니다.
**Type**
---
**페이지 구현 및 라우팅**
- 계정 찾기 페이지 (`/find-account`) UI 및 기본 로직을 구현했습니다.
- 비밀번호 찾기 페이지 (`/find-password`) UI 및 기본 로직을  구현했습니다.
- 로그인 페이지에 계정 및 비밀번호 찾기 페이지로 이동하는 링크를 추가했습니다.
- `App.tsx`에 새로운 페이지들을 위한 라우트를 추가했습니다.
**백엔드 API 연동**
-계정 찾기 페이지에 실제 백엔드 API (/api/auth/find-account) 연동
-axios를 사용한 HTTP 요청 처리
-ApiResponse<UserResponse> 구조에 맞는 응답 데이터 파싱
-환경변수를 통한 API URL 관리 (.env.production 설정)
**강화된 입력 유효성 검사**
-휴대폰 번호 실시간 포맷팅 (010-XXXX-XXXX 자동 변환)
-엄격한 정규식 기반 유효성 검사 (휴대폰 번호, 이름)
-클라이언트 사이드 사전 검증으로 보안 강화
-사용자 친화적인 에러 메시지 제공
**보안 및 환경 설정**
- .env.production을 .gitignore에 추가하여 보안 강화
- API 전송 시 데이터 최적화 (하이픈 제거)
**사용자 편의성 향상:**
사용자가 아이디나 비밀번호를 잊어버렸을 경우 쉽게 찾을 수 있는 기능 제공
**보안 및 성능 개선:**
기존 임시 로직에서 무작위 입력으로 인한 불필요한 API 호출 방지
클라이언트 사이드 검증으로 서버 리소스 보호
일관된 데이터 …

MYCE-181 feat: 계정 및 비밀번호 찾기 페이지 추가 

---

.gitignore
src/App.tsx
src/pages/auth/FindAccountPage.tsx
src/pages/auth/FindPasswordPage.tsx
src/pages/auth/LoginPage.tsx
src/pages/common/HomePage.tsx

홈페이지의 전체적인 UI 디자인을 개선하고 가독성을 높이기 위해 코드를 리팩토링했습니다.
**Type**
---
- `src/pages/common/HomePage.tsx` 파일의 UI 구조를 변경하고 스타일을
개선했습니다.
- 기존 코드의 가독성과 유지보수성을 향상시키기 위해 일부 로직을 수정하고
코드를 재구성했습니다.
- 사용자에게 더 나은 시각적 경험을 제공하고, 서비스의 첫인상을 개선하기 위해  홈페이지 디자인 변경이 필요했습니다.
- 향후 기능 추가 및 유지보수를 용이하게 하기 위해 코드 리팩토링을 진행했습니다.
---
- 홈페이지 레이아웃을 좀 더 직관적이고 현대적인 디자인으로 변경
- 컴포넌트 스타일링 방식 개선 (예: 인라인 스타일 -> 스타일 컴포넌트 또는 CSS 클래스)
- 코드 구조를 단순화하여 가독성 향상
- 
---
1. `npm start` 또는 `yarn start`로 애플리케이션을 실행합니다.
2. 브라우저에서 홈페이지(/)에 접속하여 UI가 의도한 대로 표시되는지 확인합니다.
3. 화면 크기를 조절하며 반응형 디자인이 올바르게 동작하는지 확인합니다.
---
- 관련 이슈: x
- 지라 백로그: [https://sesac-springboot.atlassian.net/browse/MYCE-184](url)
---
---

MYCE-184 refactor: homePage 화면 디자인 개선

---

.gitignore
src/components/layout/Header.tsx
src/components/layout/Sidebar.tsx
src/pages/auth/FindAccountPage.tsx
src/pages/auth/FindPasswordPage.tsx
src/pages/auth/LoginPage.tsx
src/pages/auth/SignUp.tsx
src/pages/common/HomePage.tsx
yarn.lock

로그인, 회원가입, 아이디 찾기, 비밀번호 찾기 등 인증 관련 페이지의 디자인을 홈페이지 및 전체 웹사이트 디자인 테마에 맞춰 통일감 있게 전면 수정했습니다.
**Type**
---
인증 페이지 디자인 전면 개편: 로그인, 회원가입, 아이디 찾기, 비밀번호 찾기 페이지의 디자인을 기존 파란색/보라색 계열에서 홈페이지 및 다른 화면 디자인의 어두운 배경(약간 어두운 주황색 포인트) 테마에 맞춰 전면 수정했습니다.
비밀번호 찾기 페이지 배경 강화: FindPasswordPage.tsx의 배경에 ::before 및 ::after 가상 요소를 활용하여 주황색 및 붉은색 방사형 그라데이션 효과를 추가하여 시각적 깊이와 동적인 느낌을 더했습니다.
컴포넌트 스타일 통일: 버튼, 인풋 필드, 링크 등 주요 UI 컴포넌트의 스타일과 호버 애니메이션을 수정하여 통일된 디자인 언어를 적용했습니다.
헤더 디자인 수정: 전반적인 디자인 통일성을 위해 헤더 디자인도 함께 수정했습니다.
.gitignore 파일 업데이트: .vercel 디렉토리를 추가하여 불필요한 배포 관련 파일이 Git 추적에서 제외되도록 했습니다.
전체 웹 사이트의 UI/UX를 개선하고 통일감 있는 디자인을 제공하여 사용자의 만족도를 증대시키기 위함입니다. 일관된 브랜드 경험을 제공하고 시각적으로 더 매력적인 페이지를 구현하고자 했습니다.
---
- 비밀번호 찾기 페이지 (FindPasswordPage.tsx) 디자인 수정:
Container 컴포넌트의 ::before 가상 요소 투명도(rgba(249,115,22,0.08) -> …

MYCE-197 feat: 로그인, 회원가입, 아이디, 비밀번호 찾기 페이지 디자인 개선

---

src/App.tsx
src/components/layout/Header.tsx
src/pages/admin/AdminDashboardPage.tsx.backup
src/pages/auth/FindAccountPage.tsx
src/pages/auth/MyPage.tsx

이번 PR에서는 마이페이지와 프로필 관리 관련 기능들을 개선하고 관리자 대시보드에 쿠폰 관리 기능을 추가했습니다.
**Type**
---
관리자 대시보드 쿠폰 관리 기능 추가: 사이드바 메뉴, 쿠폰 통계, 목록 조회, 생성/수정/삭제 기능
마이페이지 라우팅 개선: 쿠폰/포인트, 내 게시글, 내 댓글, 설정 메뉴 정상 작동하도록 수정
UI/UX 전반적 개선: 사이드바 애니메이션, 스크롤바 스타일링, 레이아웃 간격 조정
관리자가 사용자에게 쿠폰을 발급하고 관리할 수 있는 기능이 없었음
마이페이지에서 메뉴 클릭 시 콘텐츠가 제대로 표시되지 않는 문제 해결
관리자 대시보드의 사용자 경험 개선 필요
---
src/pages/admin/AdminDashboardPage.tsx: 쿠폰 관리 기능 추가 및 UI 개선
src/pages/auth/MyPage.tsx: 마이페이지 라우팅 로직 개선
src/App.tsx: 마이페이지 라우트 설정 수정
상태 관리: 쿠폰 데이터 상태 및 폼 상태 추가
조건부 렌더링: useLocation을 활용한 마이페이지 콘텐츠 표시
애니메이션: cubic-bezier 이징 함수로 부드러운 전환 효과
스타일링: 일관된 간격과 호버 효과로 UX 향상
---
관리자 대시보드에서 쿠폰 관리 기능 동작 확인
마이페이지 각 메뉴 클릭 시 콘텐츠 표시 확인
사이드바 애니메이션 및 반응형 레이아웃 테스트
---
- 관련 이슈:
- 지라 백로그: [https://sesac-springboot.atlassian.net/browse/MYCE-210](url)
---
현재 쿠폰 데이터는 프론트엔드 상태로만 관리 …

MYCE-210 feat: 관리자 대시보드 쿠폰 관리 기능 추가 및 UI/UX 개선

---

src/pages/feed/FeedEditPage.tsx

마이 피드 수정(Feed Update) 기능의 화면/로직을 `FeedPost` 도메인 모델과 일치하도록 리팩터링하고, **소유자만 수정/삭제가 가능**하도록 권한 처리를 강화했습니다.
**Type**
---
- `FeedEditPage`를 `FeedPost` 구조에 맞게 필드/상태를 정리
- 잘못된/레거시 필드 의존 제거 및 네이밍 통일
- 에러 처리(권한/유효성) 메시지 정비
- 목록/상세/수정 간 데이터 모델 불일치로 인해 수정 화면에서 값 불일치/에러 발생
- 비소유자에게 수정/삭제 진입 가능성이 노출되는 UI 문제
- 도메인 일관성 확보 및 유지보수성 향상
---
- **`src/pages/feed/FeedEditPage.tsx`**
- `FeedPost` 기반으로 상태/폼 값 매핑
- 소유자 판별:  
```ts
selectedPost.user.nickname === user.nickname
```
이후 액션 노출
- 불필요/레거시 필드 제거 및 명확한 프로퍼티 사용
- 예외 상황(권한/404) 안내 메시지 정비
- 도메인 변환은 서비스 레이어에서 일관 적용 (이미 반영된 `feedService` 모델에 맞춤)
- UI 가드는 프롭/로컬 상태 단계에서 **이중 체크**로 안정성 확보
- 타입 엄격화로 컴파일 타임 검증 강화
---
1. **본인 게시글 수정**
- 로그인 후 본인 게시글의 수정 화면 진입
- 기존 값이 폼에 정확히 바인딩되는지 확인
- 수정 후 저장 시 성공 토스트 및 리다이렉트 확인
2. **비소유자 게시글 진입**
- 수정/삭제 버튼 미노출 또는 접근 차단 확인
3. …

MYCE-95 : refactor/feed - 피드 수정 페이지를 FeedPost 모델과 일치하도록 정리하고, 소유자 전용 수정/삭제 동작 반영

---

src/api/productService.ts
src/components/layout/Header.tsx
src/components/products/FilterButtons.tsx
src/hooks/products/useProductList.ts
src/pages/products/Lists.tsx

상품 검색 기능 구현 및 필터링 시스템 개선을 통한 사용자 상품 발견 경험 향상
**Type**
---
- 상품 검색 API 엔드포인트 (`getFilteredProducts`) 구현
- URL 쿼리 파라미터 기반 검색 키워드 처리 (`q` 파라미터)
- 검색 결과에 따른 동적 페이지 제목 표시
- 기존 필터링 시스템과 검색 기능 통합
- 검색 상태 관리를 위한 `useProductList` 훅 개선
- 사용자가 원하는 상품을 빠르게 찾을 수 있는 핵심 기능 부재
- 카테고리 필터링만으로는 한정적인 상품 발견 경험
- 키워드 기반 검색을 통한 사용자 편의성 향상 필요
- 전자상거래 플랫폼의 기본 요구사항 충족
---
- **API 레이어**: `ProductService.getFilteredProducts()` 메서드에 `q` 파라미터 추가
- **상태 관리**: `useProductList` 훅에서 URL 검색 파라미터 추출 및 처리
- **UI 개선**: 검색 결과에 따른 동적 페이지 제목 (`"키워드" 검색 결과`)
- **라우팅**: URL 쿼리 파라미터 기반 검색 상태 관리
- **RESTful API**: `/api/products?q=검색키워드` 형태의 검색 엔드포인트 활용
- **React Router**: `useLocation`을 통한 URL 쿼리 파라미터 감지
- **상태 동기화**: URL 변경 시 자동 검색 결과 갱신 (`useEffect` 의존성 배열)
- **타입 안정성**: TypeScript 인터페이스로 검색 파라미터 타입 정의
---
1. **기본 검색 테스트**
- URL에 …

MYCE-235 feat: 상품 검색 기능

---

src/api/eventService.ts
src/api/feedService.ts
src/components/feed/FeedCard.tsx
src/components/feed/FeedDetailModal.tsx
src/components/feed/FeedLikeButton.tsx
src/components/feed/FeedList.tsx
src/components/feed/FeedVoteButton.tsx
src/components/feed/LikedUsersModal.tsx
src/contexts/AuthContext.tsx
src/hooks/useLikedPosts.ts
src/pages/auth/LoginPage.tsx
src/pages/feed/FeedCreatePage.tsx
src/pages/feed/FeedDetailPage.tsx
src/pages/feed/FeedListPage.tsx
src/pages/feed/MyFeedPage.tsx

피드 좋아요 기능을 완성하여 사용자가 피드에 좋아요를 누르고, 좋아요한 사용자 목록을 확인할 수 있으며, 로그인/로그아웃 후에도 좋아요 상태가 지속되도록 구현했습니다.
**Type**
---
- 사용자가 피드에 좋아요를 누른 후 다른 페이지로 이동하거나 새로고침하면 좋아요 상태가 사라지는 문제 해결
- 좋아요한 사용자 목록 확인 기능 부재로 인한 UX 개선
- 로그인/로그아웃 후에도 좋아요 상태가 유지되어야 하는 요구사항 충족
- 사용자가 피드에 좋아요를 누른 후 다른 페이지로 이동하거나 새로고침하면 좋아요 상태가 사라지는 문제 해결
- 좋아요한 사용자 목록 확인 기능 부재로 인한 UX 개선
- 로그인/로그아웃 후에도 좋아요 상태가 유지되어야 하는 요구사항 충족
---
- **API 추가**
- `FeedService`에 `getMyLikedFeeds()`, `getFeedLikes()` 메서드 추가
- **인증 연동**
- `AuthContext`에서 로그인 시 백엔드에서 좋아요한 피드 목록 가져오기 구현
- **페이지별 좋아요 상태 관리**
- `FeedListPage`, `MyFeedPage`, `FeedDetailPage`에서 좋아요 상태 지속성 관리
- **UI 컴포넌트**
- `LikedUsersModal` 컴포넌트 생성 → 좋아요한 사용자 목록 표시
- `FeedCard`에서 좋아요 버튼과 좋아요 개수 클릭 이벤트 분리
- **localStorage 활용**
- 클라이언트 측에서 좋아요 상태를 임시 저장해 페이지 이동 시에도 유지
- **백엔드 동기화**
- 로그인 시 백엔드에서 사용자의 좋아요 …

MYCE-97 : feat/feed - feedLikes 피드 좋아요 추가

---

src/components/order/ProductPreviewSection.tsx
src/components/products/ModernOptionSelector.tsx
src/components/products/SelectedOptions.tsx
src/hooks/order/usePaymentData.ts
src/hooks/products/useProductActions.ts
src/hooks/products/useProductOptions.ts
src/pages/products/DetailPage.tsx
src/types/order.ts

상품 상세 페이지의 `ModernOptionSelector` 컴포넌트 UI/UX 개선 및 옵션 선택 플로우 최적화
**Type**
---
- `ModernOptionSelector` 컴포넌트의 성별/색상 드롭다운 UI 개선
- 사이즈 선택 버튼의 접근성 및 시각적 피드백 향상
- 옵션 선택 상태 표시 및 품절 상품 처리 로직 개선
- 반응형 레이아웃 최적화로 모바일 UX 개선
- 기존 드롭다운 UI의 가독성 및 사용성 문제 해결
- 품절 상품에 대한 명확한 시각적 구분 필요
- 모바일 환경에서의 옵션 선택 경험 개선 필요
- 색상 표시에 컬러 인디케이터 추가로 직관성 향상
---
- **드롭다운 UI 개선**: 성별/색상 선택 드롭다운의 스타일링 및 인터랙션 개선
- **색상 표시 개선**: 색상명과 함께 컬러 인디케이터 추가 표시
- **사이즈 버튼 최적화**: 선택/품절 상태의 시각적 구분 명확화
- **반응형 레이아웃**: 모바일 환경에서 1열 배치로 변경
- **접근성 향상**: 포커스 상태 및 키보드 네비게이션 개선
- **Styled Components** 기반 컴포넌트 스타일링 최적화
- **색상 매핑 유틸리티** 함수로 브랜드 컬러 일관성 확보
- **조건부 렌더링** 로직 개선으로 성능 최적화
- **이벤트 핸들링** 개선으로 외부 클릭 시 드롭다운 자동 닫기
- **CSS Grid & Flexbox** 활용한 반응형 레이아웃 구현
---
- 다양한 상품에서 성별/색상/사이즈 옵션 선택 테스트
- 품절 상품 처리 및 시각적 피드백 확인
- 모바일/태블릿/데스크톱 환경에서 반응형 동작 검증
- …

MYCE-240 feat: 상품 상세 페이지 옵션 선택 UI 수정

---

src/api/orderService.ts
src/pages/order/SellerOrdersPage.tsx
src/pages/order/UserOrdersPage.tsx

**사용자 주문 내역 페이지에 주문 취소 및 반품 기능 구현**
**Type**
---
- UserOrdersPage에 주문 취소 및 반품 기능 추가
- 주문 상태별 액션 버튼 UI 구현 (취소/반품)
- 사용자 확인을 위한 Warning 모달 컴포넌트 연동
- OrderService에 updateUserOrderStatus API 메서드 추가
- 주문 상태에 따른 비즈니스 로직 구현
- 사용자가 자신의 주문을 직접 관리할 수 있는 기능 필요
- 고객 서비스 효율성 향상을 위한 셀프 서비스 기능 제공
- 주문 상태별로 적절한 액션(취소/반품) 제공으로 사용자 경험 개선
- 기존에는 판매자만 주문 상태를 변경할 수 있어 고객 불편 사항 존재
---
- **UI 컴포넌트 추가**: 주문 상태별 액션 버튼 (취소/반품) 렌더링
- **상태 관리 로직**: `updatingOrderId` 상태로 로딩 처리 및 중복 요청 방지
- **모달 시스템**: Warning 모달을 통한 사용자 확인 프로세스
- **비즈니스 로직**: 주문 상태에 따른 가능한 액션 결정 로직
- **API 연동**: 새로운 사용자 주문 상태 변경 API 엔드포인트 연동
- **상태별 액션 제한**: 
- `ORDERED` 상태: 취소만 가능
- `DELIVERED` 상태: 반품만 가능
- 기타 상태: 액션 불가
- **확인 모달 시스템**: 실수로 인한 잘못된 액션 방지
- **실시간 업데이트**: 상태 변경 후 주문 목록 자동 새로고침
- **에러 핸들링**: API 에러 메시지 사용자 친화적 표시
- **로딩 상태**: 개별 주문 단위로 …

MYCE-239 feat: 사용자 주문 취소 및 반품 UI 및 API 연동

---

src/components/order/ProductPreviewSection.tsx
src/components/products/ModernOptionSelector.tsx
src/components/products/SelectedOptions.tsx
src/hooks/order/usePaymentData.ts
src/hooks/products/useProductActions.ts
src/hooks/products/useProductOptions.ts
src/pages/products/DetailPage.tsx
src/types/order.ts

상품 상세 페이지의 `ModernOptionSelector` 컴포넌트 UI/UX 개선 및 옵션 선택 플로우 최적화
**Type**
---
- `ModernOptionSelector` 컴포넌트의 성별/색상 드롭다운 UI 개선
- 사이즈 선택 버튼의 접근성 및 시각적 피드백 향상
- 옵션 선택 상태 표시 및 품절 상품 처리 로직 개선
- 반응형 레이아웃 최적화로 모바일 UX 개선
- 기존 드롭다운 UI의 가독성 및 사용성 문제 해결
- 품절 상품에 대한 명확한 시각적 구분 필요
- 모바일 환경에서의 옵션 선택 경험 개선 필요
- 색상 표시에 컬러 인디케이터 추가로 직관성 향상
---
- **드롭다운 UI 개선**: 성별/색상 선택 드롭다운의 스타일링 및 인터랙션 개선
- **색상 표시 개선**: 색상명과 함께 컬러 인디케이터 추가 표시
- **사이즈 버튼 최적화**: 선택/품절 상태의 시각적 구분 명확화
- **반응형 레이아웃**: 모바일 환경에서 1열 배치로 변경
- **접근성 향상**: 포커스 상태 및 키보드 네비게이션 개선
- **Styled Components** 기반 컴포넌트 스타일링 최적화
- **색상 매핑 유틸리티** 함수로 브랜드 컬러 일관성 확보
- **조건부 렌더링** 로직 개선으로 성능 최적화
- **이벤트 핸들링** 개선으로 외부 클릭 시 드롭다운 자동 닫기
- **CSS Grid & Flexbox** 활용한 반응형 레이아웃 구현
---
- 다양한 상품에서 성별/색상/사이즈 옵션 선택 테스트
- 품절 상품 처리 및 시각적 피드백 확인
- 모바일/태블릿/데스크톱 환경에서 반응형 동작 검증
- …

MYCE-240 feat: 상품 상세 페이지 옵션 선택 수정

---

src/api/productService.ts
src/api/storeService.ts
src/components/products/FilterButtons.styles.ts
src/components/products/FilterButtons.tsx
src/hooks/products/useProductList.ts
src/pages/products/Lists.tsx
src/types/products.ts

**상품 목록 필터링 UI 및 API 연동 구현**
**Type**
---
- 상품 목록 페이지(`Lists.tsx`)에 종합적인 필터링 및 정렬 기능 구현
- 다중 조건 필터링 UI 컴포넌트(`FilterButtons.tsx`) 개발
- 실시간 상품 검색 및 필터링을 위한 API 연동 구현
- 상품 그리드, 페이지네이션, 로딩/에러 상태 처리 통합
- URL 기반 필터 상태 관리 및 브라우저 히스토리 연동
- 사용자의 상품 검색 경험 향상을 위한 직관적인 필터링 시스템 필요
- 대용량 상품 데이터를 효율적으로 탐색할 수 있는 UI/UX 구현 요구
- 카테고리, 가격대, 브랜드, 재고 등 다양한 조건으로 상품을 찾을 수 있는 기능 필요
- SEO 친화적인 URL 파라미터 기반 필터 상태 관리 구현 필요
---
- **Lists.tsx**: 상품 목록 메인 페이지 컴포넌트 구현
- useProductList 훅을 활용한 상태 관리
- 로딩/에러/빈 상태 처리
- 페이지네이션 및 정렬 기능 통합
- **FilterButtons.tsx**: 필터링 UI 컴포넌트 구현
- 정렬 옵션: 최신순, 인기순, 가격순, 할인순
- 필터 옵션: 카테고리, 스토어, 성별, 색상, 사이즈, 가격 범위
- 재고 있음/할인 상품만 보기 토글 기능
- 디바운싱을 통한 실시간 필터링 최적화
- **useProductList.ts**: 상품 목록 데이터 관리 훅
- URL 파라미터 기반 필터 상태 동기화
- ProductService API 연동
- 페이지네이션 및 정렬 상태 관리
- 에러 핸들링 및 재시도 로직
- …

MYCE-253 feat: 상품 리스트 필터링(색상, 사이즈, 성별 등등) 추가

---

src/pages/cart/WishListPage.tsx
src/pages/common/HomePage.tsx
src/pages/products/Lists.styles.ts

메인페이지에서 고정된 인기 상품 데이터를 실제 wishNumber(찜 개수) 기반 상위 4개 상품으로 동적 표시하도록 개선
**Type**
---
- 메인페이지(HomePage.tsx)에서 고정된 인기 상품 데이터를 제거하고 동적 API 호출로 변경
- ProductService.getFilteredProducts API를 활용하여 wishNumber 기준 상위 4개 상품 조회
- 기존 ProductGrid, ProductCard 컴포넌트 재사용으로 일관된 UI 유지
- 로딩, 에러, 빈 상태 처리 추가
- 인기 상품 섹션의 실시간 데이터 표시 구현
- 실제 사용자들의 찜 데이터를 기반으로 한 진짜 인기 상품 표시 필요
- 사용자 경험 향상을 위한 실시간 인기 상품 반영
- 고정된 더미 데이터에서 벗어나 실제 서비스 가치 제공
- 다른 사용자들의 관심사를 쉽게 파악할 수 있는 소셜 증명 효과
---
- HomePage.tsx에 인기 상품 상태 관리 추가 (popularProducts, loading, error)
- useEffect 훅을 사용한 컴포넌트 마운트 시 인기 상품 데이터 페칭
- ProductService.getFilteredProducts({ sort: "popular", size: 4, page: 0 }) API 호출
- 기존 ProductGrid 컴포넌트 재사용으로 일관된 UI 패턴 유지
- 로딩 상태 표시 및 에러 핸들링 구현
- 기존 ProductService API 인터페이스 완전 활용
- 현재 프로젝트에서 사용 중인 상태 관리 패턴 유지
- 기존 스타일 컴포넌트 재사용으로 디자인 …

MYCE-268 feat: 메인 페이지 인기 상품 연동

---

src/App.tsx
src/api/userProfileService.ts
src/components/feed/FeedCard.tsx
src/components/feed/FeedDetailModal.tsx
src/components/feed/FeedUserProfile.tsx
src/components/feed/FollowButton.tsx
src/components/feed/FollowListModal.tsx
src/pages/auth/MyPage.tsx
src/pages/feed/FeedDetailPage.tsx
src/pages/feed/MyFeedPage.tsx

피드 관련 페이지에서 **사용자 신체 정보 표시 기능**을 구현하고  
`FeedUserProfile` 공통 컴포넌트를 개발하여 일관된 사용자 경험을 제공합니다.
**Type**
---
**1. FeedUserProfile 공통 컴포넌트 개발**
- 사용자 신체 정보(성별, 키, 몸무게, 발 사이즈)를 표시하는 재사용 컴포넌트 구현
**2. UserProfileService 확장**
- `getUserProfileById` API 연동
**3. 피드 관련 페이지 통합**
- `FeedCard`, `FeedDetailModal`, `FeedDetailPage`, `MyFeedPage`에 `FeedUserProfile` 적용
**4. 마이피드 레이아웃 개선**
- 프로필 섹션에 실제 사용자 정보 표시
- 신체 정보 배치 최적화
**5. 프로필 수정 기능**
- 로그인한 사용자에게만 수정 버튼 표시
- 수정 버튼 클릭 시 프로필 수정 페이지로 이동
- **백엔드 API 활용**: 신체 정보 API를 프론트에서 활용
- **일관된 UX**: 모든 피드 관련 페이지에서 동일한 프로필 UI 제공
- **사용자 경험 개선**: 피드 작성자의 신체 정보로 스타일 참고 정보 제공
- **개인화**: 사용자별 맞춤형 프로필 표시로 차별화된 경험 제공
---
- **새로운 컴포넌트**: `src/components/feed/FeedUserProfile.tsx`
- **API 확장**: `src/api/userProfileService.ts` → `getUserProfileById` 추가
- **기존 컴포넌트 수정**: Feed …

MYCE-250 : feat/feed - feedUserProfile 리팩토링

---

src/App.tsx
src/api/feedService.ts
src/components/feed/FeedSearchModal.tsx
src/pages/auth/MyComments.tsx
src/pages/feed/FeedListPage.tsx

피드 **검색 기능** 및 **UI/UX 개선**을 구현했습니다.  
백엔드 **QueryDSL 검색 API**와 완벽히 연동하여 **실시간 검색**, **최근 검색어 관리**, **디바운싱 최적화**를 지원합니다.
**Type**
---
- **FeedSearchModal 컴포넌트**
- 실시간 검색 및 자동완성 지원
- 최근 검색어 저장·삭제 (로컬 스토리지 활용)
- 검색 팁 및 가이드 제공
- 로딩 상태·에러 처리 개선
- **FeedService.searchFeeds 메서드**
- 백엔드 QueryDSL 기반 API 연동
- 다중 검색 파라미터 지원  
*(q, authorId, feedType, startDate, endDate, productName, productId, eventId, eventTitle, hashtags, page, size, sort)*
- API 응답 → FE 타입 매핑 및 타입 안전성 강화
- **FeedListPage 검색 기능**
- 상단 FEED 헤더에 검색 아이콘 및 모달 연결
- 검색어 표시 및 초기화 기능
- 검색 결과 없음 UI 개선
- 디바운싱 적용으로 API 호출 최적화
- **FEED 헤더 디자인**
- text-4xl 크기 및 그라데이션 효과 적용  
*(from-[#87CEEB] → to-blue-600)*
- 검색 아이콘 확대 및 호버 애니메이션 추가
- **검색 모달 UX**
- 로딩 스피너 및 상태 메시지 표시
- 부드러운 트랜지션 및 애니메이션
- 검색 가이드 제공
- 기존 피드에서 **원하는 콘텐츠를 빠르게 찾기 어려운 문제** 해결
- …

MYCE-277 : fead/feed - 피드 검색 모달 구현 및 피드 목록 검색 피드 추가

---

src/api/addressService.ts
src/api/couponService.ts
src/api/levelService.ts
src/api/pointService.ts
src/api/userProfileService.ts
src/components/order/AddressSelectionSection.tsx
src/components/order/CouponSelectionSection.tsx
src/components/order/EnhancedPointSection.tsx
src/components/order/PaymentSummary.tsx
src/components/order/UserLevelSection.tsx
src/components/products/WishlistButton.tsx
src/hooks/order/useOrderDetail.ts
src/hooks/order/usePaymentActions.ts
src/hooks/order/usePaymentData.ts
src/pages/auth/AddressManagementPage.tsx
src/pages/auth/CouponsPage.tsx
src/pages/order/CheckoutPage.tsx
src/pages/order/PaymentPage.tsx
src/pages/seller/SellerProductManagePage.tsx
src/types/types.ts
src/utils/auth/tokenUtils.ts

주문 페이지 사용자 경험 개선 - 배송지 선택, 쿠폰 사용 기능 추가 및 전반적인 UI/UX 향상
**Type**
---
- **배송지 관리 기능 강화**: 사용자 배송지 목록 조회 및 선택 기능 구현
- **쿠폰 시스템 통합**: 사용 가능한 쿠폰 조회, 선택, 코드 입력을 통한 쿠폰 적용 기능
- **포인트 사용 개선**: 향상된 포인트 사용 UI 및 전체 포인트 사용 기능
- **데이터 로딩 최적화**: 초기 페이지 로딩 시 필요한 모든 데이터 병렬 처리
- **결제 프로세스 개선**: 쿠폰 할인 반영된 최종 금액 계산 및 결제 완료 후처리
- 사용자가 매번 배송지를 입력하는 불편함 해소 필요
- 쿠폰 혜택을 주문 과정에서 바로 활용할 수 있도록 개선 필요
- 복잡한 결제 과정의 사용자 경험 향상 필요
- 할인 혜택 적용 후 실제 결제 금액의 명확한 표시 필요
---
- `AddressSelectionSection` 컴포넌트 추가로 저장된 배송지 목록 표시 및 선택 가능
- `CouponSelectionSection` 컴포넌트 추가로 쿠폰 목록 조회 및 코드 입력 기능 제공
- `EnhancedPointSection` 컴포넌트로 포인트 사용 UI 개선
- `usePaymentData` 훅에 배송지, 쿠폰, 포인트 관련 상태 및 로직 추가
- 초기 데이터 로딩을 위한 `loadInitialData` 함수 구현
- 쿠폰 할인이 반영된 최종 금액 계산 로직 개선
- **상태 관리 통합**: 기존 결제 상태에 새로운 기능들을 자연스럽게 통합
- **API 병렬 처리**: 사용자 프로필, 배송지, 포인트, 쿠폰 …

MYCE-275 feat: 주문 페이지 (쿠폰 사용, 배송지) 추가

---

src/api/reviewService.ts
src/components/review/ProductReviews.tsx
src/components/review/ReviewCard.tsx
src/components/review/ReviewList.tsx
src/components/review/ReviewReportModal.tsx
src/hooks/review/useReviewReport.ts
src/pages/reviews/ReviewWritePage.tsx
src/types/review.ts

**Type**
---
- 리뷰 신고 모달 컴포넌트(ReviewReportModal) 구현
- 신고 상태 관리를 위한 커스텀 훅(useReviewReport) 개발
- 리뷰 신고 API 엔드포인트 연동 및 에러 처리 로직 구현
- 7가지 신고 사유 옵션 제공 (욕설/비방, 스팸, 부적절한 내용, 허위 정보, 광고, 저작권 침해, 기타)
- 로컬 스토리지를 활용한 신고된 리뷰 추적 기능
- 커뮤니티 건전성 유지를 위해 부적절한 리뷰 신고 기능이 필요
- 사용자가 스팸, 욕설, 허위 정보 등의 문제가 있는 리뷰를 신고할 수 있는 시스템 구축
- 관리자가 신고된 리뷰를 검토하고 적절한 조치를 취할 수 있도록 지원
---
- ReviewReportModal.tsx: 신고 모달 UI 컴포넌트
- 7가지 신고 사유 라디오 버튼 선택
- 상세 설명 텍스트 에어리어 (선택사항, 500자 제한)
- 로딩 상태 및 에러 처리 UI
- ESC 키 및 배경 클릭으로 모달 닫기
- useReviewReport.ts: 신고 상태 관리 훅
- 신고된 리뷰 ID 추적 (로컬 스토리지 활용)
- 중복 신고 방지 기능
- 신고 상태 초기화 기능
- reviewService.ts: API 연동
- reportReview() 메서드 구현
- 상세한 에러 처리 및 사용자 친화적 에러 메시지
- JWT 토큰 기반 인증 처리
- 상태 관리: React Hook을 활용한 모달 상태 및 폼 데이터 관리
- API 통신: axios를 통한 RESTful API 연동
- 에러 처리: HTTP 상태 코드별 세분화된 에러 메시지 제공
- UX 개선: 로딩 …

MYCE-282 : feat/reviewReport(front) - 리뷰 신고 기능 UI 구현(#183)

---

src/api/productService.ts
src/pages/products/Lists.styles.ts
src/pages/products/Lists.tsx

프론트엔드에서 상품 AI 추천 API 연동 및 프롬프트 입력 UI 구현
**Type**
---
- 백엔드 상품 AI 추천 API (`POST /api/ai/products/recommend`)와 프론트엔드 연동 완료
- 사용자 프롬프트 입력을 위한 UI 컴포넌트 구현
- AI 추천 결과를 표시하는 상품 리스트 컴포넌트 개발
- 로딩 상태 및 에러 핸들링 구현
- 사용자가 자연어로 원하는 상품을 요청할 수 있는 AI 기반 개인화 추천 기능 제공
- "편안한 러닝화", "여름용 샌들" 등의 직관적인 검색을 통한 사용자 경험 향상
- 기존의 필터 기반 검색을 보완하는 차세대 상품 발견 기능
---
- **API 연동 구현**
- axios 기반 AI 추천 API 호출 함수 구현
- Bearer Token 인증 처리
- 요청/응답 타입 정의 (TypeScript)
- **UI 컴포넌트 구현**
- 프롬프트 입력 필드 (최대 500자 제한)
- 추천 개수 선택 (1-20개)
- AI 추천 실행 버튼
- 로딩 스피너 및 상태 표시
- **상품 결과 표시**
- AI 추천 상품 카드 리스트
- 추천 이유 배지 ("AI 추천" 라벨)
- 폴백 상품과 구분되는 UI
- **상태 관리**: React useState로 프롬프트, 로딩, 결과 상태 관리
- **에러 핸들링**: API 실패 시 사용자 친화적 메시지 표시
- **응답성 UI**: 로딩 중 버튼 비활성화 및 스피너 표시
- **입력 검증**: 프롬프트 길이 제한 및 실시간 유효성 검사
---
- **기능 테스트**
- "편안한 러닝화", "여름 샌들 추천해줘" 등 …

MYCE-283 feat: 상품 AI 추천 UI 구현 및 API 연동

---

src/api/reviewService.ts
src/components/review/ReviewCard.tsx
src/hooks/review/useReviewActions.ts
src/pages/reviews/ReviewWritePage.tsx
src/types/review.ts

**Type**
---
- 리뷰 작성 완료 시 100포인트가 자동으로 적립되는 기능 구현
- 포인트 적립 안내 UI 및 성공 모달 구현
- 리뷰 작성 폼에 포인트 인센티브 배너 추가
- API 응답 타입에 포인트 정보 필드 추
- 사용자들의 리뷰 작성 참여도를 높이기 위한 인센티브 제공
- 포인트 적립을 통한 사용자 활동 촉진 및 플랫폼 활성화
- 리뷰 작성에 대한 명확한 보상 체계 구축
---
- 타입 정의 업데이트: CreateReviewResponse에 pointsEarned, currentPoints 필드 추가
- UI 컴포넌트 구현: 포인트 인센티브 배너 및 성공 모달 컴포넌트 개발
- 리뷰 작성 플로우 개선: 성공 시 포인트 정보를 포함한 모달 표시
- FormData 전송 방식 개선: 백엔드 호환성을 위한 개별 필드 전송 방식 적용
- 포인트 인센티브 배너: CSS 애니메이션과 그라디언트를 활용한 시각적 어필
- 성공 모달: 축하 애니메이션, 색종이 효과, 포인트 정보 표시
- 에러 처리: 포인트 적립 실패 시에도 리뷰 작성 성공 안내
- 상태 관리: 모달 표시/숨김 및 응답 데이터 관리
---
- 리뷰 작성 폼에서 모든 필수 필드 입력 후 제출
- 포인트 적립 성공/실패 시나리오 테스트
- 브라우저 개발자 도구를 통한 API 요청/응답 확인
- 다양한 해상도에서 UI 레이아웃 확인
---
- 관련 이슈: #188 
- 지라 백로그: MYCE-285:feat/reviewPoints(front)-리뷰 작성 시 포인트 적립 UI구현
---
- 백엔드에서 포인트 적립 로직이 완료되면 정상 동작할 예정 …

MYCE-285:feat/reviewPoints(front)-리뷰 작성 시 포인트 적립 UI구현

---

src/hooks/cart/useCartActions.ts
src/pages/cart/CartPage.tsx

장바구니에서 상품 선택/수량 변경 시 발생하던 CORS 오류와 UI 실시간 업데이트 문제를 해결했습니다.
1. **PATCH 요청 CORS 오류**: 장바구니 아이템 수정 시 `HTTP 'PATCH' is not allowed` 오류 발생
2. **선택 상태 불일치**: 새로고침 후 서버의 실제 선택 상태가 반영되지 않음
3. **UI 실시간 업데이트 실패**: 수량 변경 시 새로고침해야만 변경사항이 반영됨
**File**: `src/pages/cart/CartPage.tsx`
- **Before**: 무조건 모든 아이템을 선택 상태로 설정
- **After**: 서버에서 받은 실제 `selected` 상태를 반영
```typescript
// 기존: 모든 아이템을 강제 선택
setSelectedItems(cartData.items.map((item) => item.cartItemId));
// 수정: 서버의 실제 선택 상태 반영
const selectedItemIds = cartData.items
.filter((item) => item.selected)
.map((item) => item.cartItemId);
setSelectedItems(selectedItemIds);
```
**File**: `src/hooks/cart/useCartActions.ts`
- **개별 아이템 선택** (`handleSelectItem`)
- try-catch 블록 추가
- 서버 업데이트 우선, 성공 시에만 로컬 상태 업데이트
- 실패 시 서버 데이터로 자동 롤백
- **전체 선택** (`handleSelectAll`) …

MYCE-290 fix: 장바구니 페이지 수량 변경 실시간 반영 안 됨 수정

---

src/components/layout/Footer.tsx
src/pages/common/HomePage.tsx

홈페이지 및 푸터의 전반적인 UI/UX 디자인을 개선합니다.
**Type**
---
- 홈페이지의 전체적인 레이아웃과 컴포넌트 디자인을 현대적인
스타일로 수정했습니다.
- 푸터의 정보 구조를 개선하고 디자인을 깔끔하게 다듬었습니다.
- 기존 디자인의 가독성과 사용자 편의성을 높여 전반적인 사용자
경험을 향상시키기 위해 필요했습니다.
- 최신 트렌드에 맞는 시각적 개선을 통해 서비스의 매력도를 높이고자
합니다.
---
- **홈페이지**: 메인 배너, 상품 목록, 피드 섹션의 UI를 개선하여
시각적 계층 구조를 명확히 했습니다.
- **푸터**: 링크와 정보를 카테고리별로 재분류하고, 간결한 디자인을
적용했습니다.
- **공통**: 전반적인 컬러 팔레트와 타이포그래피를 조정하여 일관성을
확보했습니다.
- `styled-components`와 `theme.ts`를 활용하여 전역 스타일을
업데이트했습니다.
- 재사용 가능한 컴포넌트들의 스타일을 수정하여 여러 페이지에
일관되게 적용되도록 했습니다.
---
- 로컬 환경에서 `npm start`로 개발 서버를 실행하여 각 화면의
디자인이 의도대로 표시되는지 확인했습니다.
- 다양한 화면 크기(데스크톱, 태블릿, 모바일)에서 반응형 디자인이
깨지지 않는지 브라우저 개발자 도구를 통해 검사했습니다.
---
- 관련 이슈:
- 지라 백로그: [https://sesac-springboot.atlassian.net/browse/MYCE-291](url)
---
- 이번 변경은 주로 시각적인 부분에 집중되어 기능적 로직 변경은
없습니다.
- 리뷰 시 디자인의 일관성이나 …

MYCE-291 feat: 홈페이지 및 푸터 디자인 개선

---

src/pages/cart/CartPage.styles.ts
src/pages/cart/CartPage.tsx
src/pages/order/PaymentPage.styles.ts
src/pages/order/SellerOrdersPage.tsx
src/pages/order/UserOrdersPage.tsx
src/pages/products/DetailPage.styles.ts
src/pages/products/Lists.styles.ts
src/pages/products/Lists.tsx

상품, 주문, 장바구니 페이지 디자인 개선
**Type**
---
상품, 주문, 장바구니 페이지 디자인 개선
사용자 만족도를 높이기 위해 페이지 디자인을 좀 더 전체 컨셉과 어울리도록 심플하고 깔끔하게 개선했습니다.

MYCE-293 refactor: 상품, 주문, 장바구니 페이지 디자인 개선

---

src/api/userService.ts
src/pages/auth/LoginPage.tsx
src/pages/auth/ResetPasswordPage.tsx
src/pages/auth/SignUp.tsx
src/pages/auth/WithdrawPage.tsx

사용자 인증 관련 기능들을 개선하고 버그를 수정하여 더 나은 사용자 경험을 제공합니다.
**Type**
---
1. **회원가입 폼 개선** (`src/pages/auth/SignUp.tsx`)
- 전화번호 입력을 11자리 숫자로 제한하는 단일 입력창으로 변경
- 숫자만 입력 가능하도록 자동 필터링 (`handlePhoneChange` 함수 추가)
- 하이픈(-) 자동 제거 및 11자리 제한
- 실시간 유효성 검사 및 사용자 피드백 개선
2. **비밀번호 찾기 기능 수정** (`src/pages/auth/ResetPasswordPage.tsx`)
- 백엔드 토큰 검증 실패 시에도 페이지 표시하도록 개선
- 에러 처리 로직 강화로 사용자 경험 향상
- 토큰 검증 실패 시에도 비밀번호 재설정 폼 제공
3. **로그인 에러 메시지 개선** (`src/pages/auth/LoginPage.tsx`)
- 백엔드 에러 메시지에 따른 구체적인 사용자 피드백 제공
- "인증이 필요" 대신 상황별 맞춤 메시지 표시
4. **회원 탈퇴 기능 디버깅** (`src/pages/auth/WithdrawPage.tsx`, `src/api/userService.ts`)
- 디버그 로그 추가로 백엔드 통신 문제 진단
- 구체적인 에러 메시지 제공
1. **전화번호 입력 불편함**: 하이픈 입력으로 인한 사용자 불편 해결
2. **비밀번호 찾기 페이지 미표시**: 백엔드 검증 실패 시에도 페이지 표시
3. **모호한 에러 메시지**: 구체적이고 명확한 에러 메시지 제공
4. **회원 탈퇴 디버깅**: 백엔드 통신 문제 진단을 위한 로그 …

MYCE-149 refactor: 전화번호 입력 개선 및 비밀번호 찾기 기능 수정

---

src/api/couponService.ts
src/components/order/CouponSelectionSection.tsx
src/hooks/order/usePaymentActions.ts
src/hooks/order/usePaymentData.ts
src/pages/auth/CouponsPage.tsx

쿠폰 기능 관련 오류를 해결하고 코드 안정성을 개선합니다.
**Type**
---
- `couponService`에서 사용 가능한 쿠폰을 조회할 때 잘못된 상태
값을 사용하던 문제를 수정했습니다. (`ACTIVE` -> `AVAILABLE`)
- 쿠폰 사용 API (`useCoupon`) 호출 시 필수 파라미터인
`orderAmount`가 누락되었던 문제를 해결했습니다.
- `CouponsPage`에서 API 응답 데이터 처리 방식을 개선하여 다양한
필드명에 대응하고 안정성을 높였습니다.
- `CouponSelectionSection`의 날짜 포맷팅 함수에 예외 처리를
추가했습니다.
- 전반적인 코드 포맷팅을 정리했습니다.
기존 쿠폰 기능은 다음과 같은 여러 오류를 포함하고 있었습니다.
1.  사용 가능한 쿠폰 목록을 정상적으로 불러오지 못하는 문제
2.  주문 시 쿠폰을 적용하면 오류가 발생하는 문제
3.  API 응답 구조 변경 시 쿠폰 정보가 올바르게 표시되지 않는 문제
이번 수정을 통해 사용자가 원활하게 쿠폰을 조회하고 주문에 적용할
수 있도록 핵심적인 오류들을 해결하고 코드의 안정성을
강화했습니다.
---
- **`api/couponService.ts`**: `getAvailableCoupons` 함수가
`"AVAILABLE"` 상태의 쿠폰을 요청하도록 수정
- **`hooks/order/usePaymentActions.ts`**:
`couponService.useCoupon` 호출 시 `orderAmount` 파라미터를 추가
- **`hooks/order/usePaymentData.ts`**: …

fix: 쿠폰 기능 관련 오류 수정

---

src/api/couponService.ts
src/components/order/CouponSelectionSection.tsx
src/hooks/order/usePaymentActions.ts
src/hooks/order/usePaymentData.ts

주문 페이지에서 쿠폰 목록 API를 불러오지 못할 때 다른 기능인 배송지 선택, 유저 프로필 자동 입력이 안 되는 오류를 수정했습니다.
**Type**

MYCE-293 fix: 주문 페이지에서 쿠폰 목록 없을 시 배송지 선택, 유저 프로필 자동 입력 안 되는 오류 수정
